# Generated by Django 2.2.4 on 2019-08-31 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('recording', models.FileField(upload_to='registration')),
                ('submit_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
